---
title: CA2124. Ограничьте уязвимые предложения finally во внешних блоках try
description: В версиях 1,0 и 1,1 платформа .NET Framework, Открытый или защищенный метод содержит блок try/catch/finally. Блок finally сбрасывает состояние безопасности и не заключен в блок finally.
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: mikejo5000
ms.author: mikejo
manager: jmartens
ms.workload:
- multiple
ms.openlocfilehash: ab236c2bfa37752e29c5b4179025837b9843f280
ms.sourcegitcommit: 8590cf6b3351e82827fd21159beefef0c02bf162
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 03/08/2021
ms.locfileid: "102469005"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124. Ограничьте уязвимые предложения finally во внешних блоках try

|Элемент|Значение|
|-|-|
|Идентификатор правила|CA2124|
|Категория|Microsoft.Security|
|Критическое изменение|Не критическое|

## <a name="cause"></a>Причина
В версиях 1,0 и 1,1 платформа .NET Framework, Открытый или защищенный метод содержит `try` / `catch` / `finally` блок. `finally`Блок будет сброшен в состояние безопасности и не заключен в `finally` блок.

> [!NOTE]
> Это правило было признано устаревшим. Дополнительные сведения см. в разделе [устаревшие правила](fxcop-unported-deprecated-rules.md).

## <a name="rule-description"></a>Описание правила
Это правило находит `try` / `finally` в коде блоки, предназначенные для версий 1,0 и 1,1 платформа .NET Framework, которые могут быть уязвимы для фильтров вредоносных исключений, имеющихся в стеке вызовов. Если конфиденциальные операции, такие как олицетворение, происходят в блоке try и создается исключение, то фильтр может выполняться перед `finally` блоком. Для примера олицетворения это означает, что фильтр будет выполняться от имени олицетворяемого пользователя. Фильтры в настоящее время реализуются только в Visual Basic.

> [!NOTE]
> В версиях 2,0 и более поздних платформа .NET Framework среда выполнения автоматически защищает `try` / `catch` /  `finally` блок от вредоносных фильтров исключений, если сброс происходит непосредственно в методе, содержащем блок исключения.

## <a name="how-to-fix-violations"></a>Устранение нарушений
Поместите развернутый объект `try` / `finally` во внешний блок try. См. Второй пример, приведенный ниже. Это приводит `finally` к выполнению действия до выполнения кода фильтрации.

## <a name="when-to-suppress-warnings"></a>Когда следует подавлять предупреждения
Для этого правила отключать вывод предупреждений не следует.

## <a name="pseudo-code-example"></a>Пример псевдо-кода

### <a name="description"></a>Описание

В приведенном ниже псевдокоде показан шаблон, обнаруживаемый этим правилом.

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

В следующем псевдокоде показан шаблон, который можно использовать для защиты кода и удовлетворения этого правила.

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```
